name: CI Test

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    services:
      elasticmq:
        image: softwaremill/elasticmq
        ports:
          - 9324:9324
        # options: -p 9324:9324 -v /tmp/elasticmq:/opt/elasticmq --name elasticmq
    steps:
      - uses: actions/checkout@v4
        name: Checkout code
      - run: sudo cp ${{ github.workspace }}/elasticmq.conf /tmp/elasticmq.conf
      # - name: Restart elasticmq
      #   uses: docker://docker
      #   with:
      #     args: docker restart elasticmq
      - name: Start ElasticMQ container with custom config
        run: |
          docker run -d -p 9324:9324 \
          -v /tmp/elasticmq.conf:/opt/elasticmq.conf \
          --name elasticmq
      - uses: actions/setup-node@v4
        name: Use Node.js ${{ matrix.node-version }}
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: npm i
      - name: check lint
        run: npm run lint
      - name: npm test
        env:
          SQS_ENDPOINT: http://localhost:9324
        run: npm run test
