name: CI Test

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    services:
      elasticmq:
        image: softwaremill/elasticmq
        options: -p 9324:9324 -v ${{ github.workspace }}/elasticmq.conf:/opt/elasticmq.conf --name elasticmq
    steps:
      - uses: actions/setup-node@v4
        name: Use Node.js ${{ matrix.node-version }}
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: npm i
      - name: check lint
        run: npm run lint
      - name: npm test
        env:
          SQS_ENDPOINT: http://localhost:9324
        run: npm run test
